In [ ]:
# Importamos la libreria pandas
import pandas as pd

Página web: https://www.football-data.co.uk/data.php

# 1. Leer archivo csv de la página web

In [ ]:
# Leemos el archivo csv de la página
df_England_soccer = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")

In [ ]:
# Mostrar el dataset
df_England_soccer.head()

  Div        Date   Time    HomeTeam  ... MaxCAHH  MaxCAHA  AvgCAHH AvgCAHA
0  E0  13/08/2021  20:00   Brentford  ...    2.05     2.17     1.80    2.09
1  E0  14/08/2021  12:30  Man United  ...    2.19     1.93     2.10    1.79
2  E0  14/08/2021  15:00     Burnley  ...    1.82     2.19     1.79    2.12
3  E0  14/08/2021  15:00     Chelsea  ...    2.16     1.93     2.06    1.82
4  E0  14/08/2021  15:00     Everton  ...    2.08     1.90     2.03    1.86

[5 rows x 106 columns]

# 2. Leer csv de multiples urls con pandas

- https://www.football-data.co.uk/mmz4281/2122/E0.csv
- https://www.football-data.co.uk/mmz4281/2122/E1.csv

In [ ]:
# Cremos el root
root = "https://www.football-data.co.uk/mmz4281/"

### Multiples ligas

- https://www.football-data.co.uk/mmz4281/2122/E0.csv
- https://www.football-data.co.uk/mmz4281/2122/E1.csv
- https://www.football-data.co.uk/mmz4281/2122/E2.csv
- https://www.football-data.co.uk/mmz4281/2122/E3.csv
- https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [ ]:
# Cremoa la variable ligas
leagues = ["E0", "E1", "E2", "E3", "EC"]
frames = []

for league in leagues:
  df = pd.read_csv(root + "2122" + "/" + league + ".csv", encoding="unicode_escape")
  frames.append(df)

In [ ]:
# Tamaño de frames
len(frames)

5

In [ ]:
# Mostrar el 1er elemento
frames[0]

    Div        Date   Time    HomeTeam  ... MaxCAHH  MaxCAHA  AvgCAHH AvgCAHA
0    E0  13/08/2021  20:00   Brentford  ...    2.05     2.17     1.80    2.09
1    E0  14/08/2021  12:30  Man United  ...    2.19     1.93     2.10    1.79
2    E0  14/08/2021  15:00     Burnley  ...    1.82     2.19     1.79    2.12
3    E0  14/08/2021  15:00     Chelsea  ...    2.16     1.93     2.06    1.82
4    E0  14/08/2021  15:00     Everton  ...    2.08     1.90     2.03    1.86
..   ..         ...    ...         ...  ...     ...      ...      ...     ...
186  E0  02/01/2022  14:00   Brentford  ...    2.21     1.92     2.03    1.86
187  E0  02/01/2022  14:00     Everton  ...    2.13     2.07     2.00    1.88
188  E0  02/01/2022  14:00       Leeds  ...    2.14     1.90     2.06    1.84
189  E0  02/01/2022  16:30     Chelsea  ...    2.01     2.06     1.90    1.98
190  E0  03/01/2022  17:30  Man United  ...    2.00     2.15     1.90    1.99

[191 rows x 106 columns]

# 2.1 Multiples temporadas

In [ ]:
leagues = ['E0','E2', 'E3']

frames = []

# hacer loop a un rango de temporadas e insertar una nueva columna
for league in leagues:
    for season in range(15,21): # rango de temporadas
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
#         df['season'] = season
        df.insert(1, 'season', season)
        frames.append(df)

In [ ]:
# total de frames (6 temporadas x 3 ligas)
len(frames)

18

In [ ]:
# mostrar 1er y ultimo elemento (columna season fue creada)
frames[17]

    Div  season        Date   Time  ... MaxCAHH MaxCAHA  AvgCAHH  AvgCAHA
0    E3      20  12/09/2020  15:00  ...    1.98    1.99     1.91     1.92
1    E3      20  12/09/2020  15:00  ...    2.09    1.90     2.00     1.83
2    E3      20  12/09/2020  15:00  ...    2.20    1.82     2.09     1.76
3    E3      20  12/09/2020  15:00  ...    2.04    1.90     1.99     1.84
4    E3      20  12/09/2020  15:00  ...    1.88    2.09     1.83     2.00
..   ..     ...         ...    ...  ...     ...     ...      ...      ...
547  E3      20  08/05/2021  15:00  ...    1.95    2.07     1.85     1.97
548  E3      20  08/05/2021  15:00  ...    1.87    2.14     1.77     2.07
549  E3      20  08/05/2021  15:00  ...    1.97    1.97     1.91     1.91
550  E3      20  08/05/2021  15:00  ...    2.08    1.89     2.01     1.82
551  E3      20  08/05/2021  16:00  ...    2.01    1.96     1.96     1.86

[552 rows x 107 columns]

# Organizar Data en un Diccionario

In [ ]:
# crear un diccionario 
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [ ]:
# obtener un elemento del diccionario
dict_countries['German Bundesliga']

'D1'

In [ ]:
dict_historical_data = {} 

# hacer loop sobre llaves de diccionario
for league in dict_countries:
    frames = [] # un dataframe por liga
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1, 'season', season)
        frames.append(df)
    df_frames = pd.concat(frames) # almacenar todas las temporadas de la liga en un solo dataframe
    dict_historical_data[league] = df_frames # asignar dataframe a un nuevo diccionario

In [ ]:
# mostrar dataframe 
dict_historical_data['Spanish La Liga']

     Div  season        Date     HomeTeam  ... MaxCAHH  MaxCAHA  AvgCAHH AvgCAHA
0    SP1      15    21/08/15       Malaga  ...     NaN      NaN      NaN     NaN
1    SP1      15    22/08/15   Ath Madrid  ...     NaN      NaN      NaN     NaN
2    SP1      15    22/08/15      Espanol  ...     NaN      NaN      NaN     NaN
3    SP1      15    22/08/15    La Coruna  ...     NaN      NaN      NaN     NaN
4    SP1      15    22/08/15    Vallecano  ...     NaN      NaN      NaN     NaN
..   ...     ...         ...          ...  ...     ...      ...      ...     ...
375  SP1      20  22/05/2021      Osasuna  ...    2.07     1.96     1.98    1.88
376  SP1      20  22/05/2021  Real Madrid  ...    2.02     2.02     1.95    1.92
377  SP1      20  22/05/2021   Valladolid  ...    1.95     2.06     1.90    1.97
378  SP1      20  23/05/2021      Granada  ...    1.84     2.23     1.77    2.12
379  SP1      20  23/05/2021      Sevilla  ...    2.13     2.03     1.99    1.88

[2280 rows x 127 columns]